
clean:
	rm -f netemu/*.o *.elf *.bin netemu/*.map ps2emu/src/*.o lv1/src/*.o debug/src/*.o *.self *.elf

all:
	# make -f netemu/Makefile_net clean
	make -f netemu/Makefile_net --no-print-directory

	rm -f netemu/*.o *.elf *.bin netemu/*.map ps2emu/src/*.o lv1/src/*.o debug/src/*.o temp.self temp.elf

